// <auto-generated />
namespace RestaurantNew.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class New_2304 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New_2304));
        
        string IMigrationMetadata.Id
        {
            get { return "201704231625325_New_2304"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
